name: Node CI
on:
    pull_request:
        branches:
            - master
jobs:
    credentials:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
                  aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
                  aws-region: ap-southeast-2
    build:
        runs-on: ubuntu-latest
        needs: credentials
        steps:
            - name: build
              uses: matt-tyler/aws-codebuild-run-project@master
              with:
                  project-name: Build-myapp-Node
    test:
        runs-on: ubuntu-latest
        needs: credentials
        steps:
            - name: test
              uses: matt-tyler/aws-codebuild-run-project@master
              with:
                  project-name: Test-myapp-Node
    lint:
        runs-on: ubuntu-latest
        needs: credentials
        steps:
            - name: lint
              uses: matt-tyler/aws-codebuild-run-project@master
              with:
                  project-name: Lint-myapp-Node
